cmake_minimum_required(VERSION 3.14)
set(CMAKE_SYSTEM_PROCESSOR "${TEST_PROCESSOR}")
include("${PROJECT_SOURCE_DIR}/cmake/livox_sdk.cmake")
if(TEST_PROCESSOR MATCHES "^(x86_64|amd64)$")
  set(expected_arch x86)
else()
  set(expected_arch arm)
endif()
if(NOT LIVOX_SDK_ARCH STREQUAL expected_arch)
  message(FATAL_ERROR "Expected ${expected_arch}, selected ${LIVOX_SDK_ARCH}")
endif()
