# Select by the CMake TARGET architecture (also works with a cross toolchain).
function(livox_sdk_arch processor out_arch out_machine)
  string(TOLOWER "${processor}" processor)
  if(processor MATCHES "^(x86_64|amd64)$")
    set(arch x86)
    set(machine "3e00")
  elseif(processor MATCHES "^(aarch64|arm64)$")
    set(arch arm)
    set(machine "b700")
  else()
    message(FATAL_ERROR "Unsupported Livox SDK architecture '${processor}'. Bundled SDKs support x86-64 and ARM64 only (not 32-bit ARM/x86).")
  endif()
  set(${out_arch} "${arch}" PARENT_SCOPE)
  set(${out_machine} "${machine}" PARENT_SCOPE)
endfunction()

livox_sdk_arch("${CMAKE_SYSTEM_PROCESSOR}" LIVOX_SDK_ARCH LIVOX_SDK_ELF_MACHINE)
set(LIVOX_SDK_ROOT "" CACHE PATH "Optional Livox SDK prefix containing include/ and lib/; empty selects by target architecture")
if(NOT LIVOX_SDK_ROOT)
  # Unified workspace, then the original livox_ros_space layout.
  foreach(candidate "${PROJECT_SOURCE_DIR}/../../livox-sdk-${LIVOX_SDK_ARCH}"
                    "${PROJECT_SOURCE_DIR}/../../../livox-sdk-${LIVOX_SDK_ARCH}")
    if(EXISTS "${candidate}/include/livox_lidar_api.h" AND IS_DIRECTORY "${candidate}/lib")
      get_filename_component(LIVOX_SDK_ROOT "${candidate}" ABSOLUTE)
      break()
    endif()
  endforeach()
endif()
if(NOT LIVOX_SDK_ROOT)
  message(FATAL_ERROR "livox-sdk-${LIVOX_SDK_ARCH} not found. Copy it into the workspace root or pass -DLIVOX_SDK_ROOT=/absolute/sdk/path.")
endif()
get_filename_component(LIVOX_SDK_ROOT "${LIVOX_SDK_ROOT}" ABSOLUTE)
# Never reuse cached find results or silently fall back to /usr/local.
unset(LIVOX_LIDAR_SDK_LIBRARY CACHE)
unset(LIVOX_LIDAR_SDK_INCLUDE_DIR CACHE)
find_library(LIVOX_LIDAR_SDK_LIBRARY
  NAMES livox_lidar_sdk_shared livox_lidar_sdk_static
  PATHS "${LIVOX_SDK_ROOT}/lib" NO_DEFAULT_PATH)
find_path(LIVOX_LIDAR_SDK_INCLUDE_DIR NAMES livox_lidar_api.h
  PATHS "${LIVOX_SDK_ROOT}/include" NO_DEFAULT_PATH)
if(NOT LIVOX_LIDAR_SDK_LIBRARY OR NOT LIVOX_LIDAR_SDK_INCLUDE_DIR)
  message(FATAL_ERROR "Incomplete SDK at '${LIVOX_SDK_ROOT}': require include/livox_lidar_api.h and lib/liblivox_lidar_sdk_{shared.so,static.a}.")
endif()
foreach(header livox_lidar_api.h livox_lidar_cfg.h livox_lidar_def.h)
  if(NOT EXISTS "${LIVOX_LIDAR_SDK_INCLUDE_DIR}/${header}")
    message(FATAL_ERROR "SDK header missing: ${LIVOX_LIDAR_SDK_INCLUDE_DIR}/${header}")
  endif()
endforeach()
# Catch a wrong override before the linker emits 'file in wrong format'.
if(LIVOX_LIDAR_SDK_LIBRARY MATCHES "\\.so$")
  file(READ "${LIVOX_LIDAR_SDK_LIBRARY}" elf_header LIMIT 20 HEX)
  string(SUBSTRING "${elf_header}" 0 12 elf_ident)
  string(SUBSTRING "${elf_header}" 36 4 elf_machine)
  if(NOT elf_ident STREQUAL "7f454c460201" OR NOT elf_machine STREQUAL LIVOX_SDK_ELF_MACHINE)
    message(FATAL_ERROR "SDK architecture mismatch: target ${CMAKE_SYSTEM_PROCESSOR}, library ${LIVOX_LIDAR_SDK_LIBRARY} (ELF machine ${elf_machine}).")
  endif()
endif()
message(STATUS "Livox SDK: target=${CMAKE_SYSTEM_PROCESSOR}, root=${LIVOX_SDK_ROOT}, library=${LIVOX_LIDAR_SDK_LIBRARY}")
